url: https://blog.amarahub.org
title: Field Notes | Amara Hub
subtitle: Skills, knowledge and opportunity.
permalink: /:year/:month/:day/:title/
baseurl: "" # the subpath of your site, e.g. /blog/

subscribe_rss: /feed.xml

exclude: ["vendor", "LICENSE", "_posts/LICENSE", "README.md"]

plugins: ["jekyll-redirect-from", "jekyll-paginate"]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

paginate: 10
paginate_path: "/page:num/"

recent_posts: 5
excerpt_link: "Read More"
titlecase: true
category_dir: categories

authors:
  amarahub:
    name: Amara Hub Team
    site: https://amarahub.org
    
include: ["CNAME"]
